micronaut:
  application:
    name: tacticalDepot

datasources:
  default:
    url: jdbc:mysql://localhost:3306/tactical_depot
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true